install:
	npm install
publish:
	npm publish --dry-run | npm link
lint:
	npx eslint .
test:
	npm test

i-linter:
	npm install -D eslint eslint-config-airbnb-base eslint-plugin-import eslint-plugin-jest